name = "FluxTraining"
uuid = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
authors = ["lorenzoh <lorenz.ohly@gmail.com>"]
version = "0.3.5"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
EarlyStopping = "792122b4-ca99-40de-a6bc-6742525f08b6"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
InlineTest = "bd334432-b1e7-49c7-a2dc-dd9149e4ebd6"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ValueHistories = "98cad3c8-aec3-5f06-8e41-884608649ab7"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BSON = "0.2, 0.3"
ChainRulesCore = "1"
DataStructures = "0.18"
EarlyStopping = "0.1, 0.2, 0.3"
Flux = "0.11, 0.12, 0.13"
Glob = "1.3"
Graphs = "1"
ImageCore = "0.8, 0.9"
InlineTest = "0.2"
OnlineStats = "1.5"
Optimisers = "0.2"
ParameterSchedulers = "0.3.1"
Parameters = "0.12"
PrettyTables = "1, 1.1, 1.2, 2"
ProgressMeter = "1.4"
Reexport = "1.0"
Setfield = "0.8, 1"
SnoopPrecompile = "1"
TensorBoardLogger = "0.1"
ValueHistories = "0.5"
Zygote = "0.6"
julia = "1"

[pollen]
title = "FluxTraining.jl"
url = "https://github.com/FluxML/FluxTraining.jl"
